// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
    const Banner: typeof import("./components/Banner.svelte")["default"]
}

export {}
